START_TRAIN_AT_IMG_SIZE: 128
DATASET: celeb_dataset
CHECKPOINT_GEN: generator.pth
CHECKPOINT_CRITIC: critic.pth
DEVICE: cuda if torch.cuda.is_available() else cpu
SAVE_MODEL: true
LOAD_MODEL: false
LEARNING_RATE: 1e-3
LEARNING_DECAY_RATE: 0.5
WARMUP_RATIO: 0.01
GRADIENT_ACCUMULATION_STEPS: 1
BATCH_SIZES:
  - 32
  - 32
  - 32
  - 16
  - 16
  - 16
  - 16
  - 8
  - 4
CHANNELS_IMG: 3
Z_DIM: 256
IN_CHANNELS: 256
CRITIC_ITERATIONS: 1
LAMBDA_GP: 10
PROGRESSIVE_EPOCHS:
  - 30
  - 30
  - 30
  - 30
  - 30
  - 30
  - 30
  - 30
  - 30
FIXED_NOISE:
  - - 8
      - Z_DIM
      - 1
      - 1
NUM_WORKERS: 4
